name: WeaponsAddon
version: '${project.version}'
main: com.Chagui68.weaponsaddon.WeaponsAddon
api-version: 1.20
depend: [Slimefun]
author: Chagui68
description: Military weapons and machines addon for Slimefun

commands:
  weapons:
    description: Main command for WeaponsAddon
    usage: /weapons <delete|summon|give> <args>
    permission: militaryarsenal.admin
    permission-message: You don't have permission to use this command!
  resetarena:
    description: Manually reset/destroy the Heavy Gunner arena
    usage: /resetarena
    permission: militaryarsenal.admin
    permission-message: You don't have permission to use this command!

permissions:
  militaryarsenal.admin:
    description: Access to admin commands
    default: op
