name: WeaponsAddon
version: 1.0
main: com.Chagui68.weaponsaddon.WeaponsAddon
api-version: 1.20
depend: [Slimefun]
author: Chagui68
description: Military Weapons Addon for Slimefun - Built for Minecraft 1.20.6
website: https://github.com/Chagui68/WeaponsAddon
